### ISSUE TITLE
大佬帮忙！

### ISSUE THREAD

**Issue by sbwml** [0ranko0P/device_xiaomi_msm8998-common#1]
https://github.com/AOSP-11/device_xiaomi_msm8998-common/tree/11/Dirac

有没有什么方法让 Dirac 默认是开启状态？

**Comment by 0ranko0P** [comment]
我没有订阅这个仓库, 刚刚才看见大佬的issue 😅

**Comment by sbwml** [comment]
牛逼 ！pick 完成
